#!/usr/bin/env bash

# This script configures a case to demonstrate the integration of mam4xx with
# eamxx. It's associated with the following GitHub issue:
# https://github.com/eagles-project/mam4xx/issues/169

# -----------------
#  Case Parameters
# -----------------

SCREAM_ROOT=~/projects/sandia/scream/
SCREAM_INPUT_ROOT=~/projects/sandia/scream-input/
MACHINE=trippy
COMPSET=F2010-SCREAMv1
RES=ne4pg2_ne4pg2
PECOUNT=1x16
CASE_NAME=${COMPSET}.${RES}.${PECOUNT}.mam4xx_nuc

# -----------------
#  Case Generation
# -----------------

# generate the case directory
${SCREAM_ROOT}/cime/scripts/create_newcase \
  --case ${CASE_NAME} \
  --compset ${COMPSET} \
  --extra-machines-dir $PWD \
  --machine ${MACHINE} \
  --pecount ${PECOUNT} \
  --res ${RES}

# ---------------------
#  Simulation Settings
# ---------------------

cd ${CASE_NAME}

# change CIME settings to reflect our particular simulation
# (see https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/3386015745/How+To+Run+SCREAMv1
#  for examples)
./xmlchange DEBUG=TRUE #debug rather than optimized build
./xmlchange STOP_OPTION=ndays # units of simulation length
./xmlchange STOP_N=1 # number of units specifying simulation length (e.g. days)

# Fiddle with CMake build options. Note that we must specify the following in addition to
# whatever else we want:
#  SCREAM_NP - the number of GLL points per side of an element (always 4)
#  SCREAM_NUM_VERTICAL_LEV - the number of vertical levels (usually 72 or 128)
#  SCREAM_NUM_TRACERS - the number of atmospheric tracers (usually 10, more with aerosols)
./xmlchange SCREAM_CMAKE_OPTIONS="SCREAM_ENABLE_MAM ON SCREAM_NP 4 SCREAM_NUM_VERTICAL_LEV 72 SCREAM_NUM_TRACERS 10"

# --------------------
#  Case Configuration
# --------------------

# set up the case
./case.setup

# set initial conditions for H2SO4 gas, aerosol tracers, and wind velocities
INPUTDATA_DIR=../e3sm-inputdata/atm/scream/init/
ORIG_IC_FILE=${INPUTDATA_DIR}/screami_ne4np4L72_20220823.nc
NEW_IC_FILE=${PWD}/screami_ne4np4L72_20220823_aero.nc

../add_aerosol_ics ${ORIG_IC_FILE} ${NEW_IC_FILE}
./atmchange initial_conditions::Filename=${NEW_IC_FILE}

# write a CMake file to point to NetCDF libraries and set some compiler flags
cat <<EOF > cmake_macros/gnu_${MACHINE}.cmake
set(SUPPORTS_CXX "TRUE")
string(APPEND FFLAGS " -fallow-argument-mismatch -Wno-implicit-interface -fallow-invalid-boz ")
string(APPEND CXX_LIBS " -lstdc++")
if (NOT DEBUG)
  string(APPEND FFLAGS " -O2")
  string(APPEND CFLAGS " -O2")
endif()
string(APPEND SLIBS " -L\$ENV{PNETCDF_PATH}/lib -lpnetcdf")
set(NETCDF_C_PATH "\$ENV{NETCDF_C_PATH}")
set(NETCDF_FORTRAN_PATH "\$ENV{NETCDF_FORTRAN_PATH}")
set(PNETCDF_PATH "\$ENV{PNETCDF_PATH}")
EOF

# write a CMake file to allow SCREAM to build locally
cat <<EOF > ${SCREAM_ROOT}/components/eamxx/cmake/machine-files/${MACHINE}.cmake
include(\${CMAKE_CURRENT_LIST_DIR}/common.cmake)
common_setup()

set(SCREAM_INPUT_ROOT "${SCREAM_INPUT_ROOT}" CACHE STRING "")
EOF

# show the case configuration
./preview_run

# ------------
#  Case Build
# ------------

./case.build

# change out of the case directory
cd ..
